// Thin wrapper around phosphor-react-native: reference icons by kebab-case name.
import React from 'react';
import {
  House,
  ForkKnife,
  ShoppingCartSimple,
  Snowflake,
  GearSix,
  User,
  Users,
  HouseLine,
  CookingPot,
  CheckCircle,
  Check,
  Plus,
  PlusCircle,
  MinusCircle,
  Bell,
  BellRinging,
  Drop,
  Cube,
  Plant,
  Carrot,
  Egg,
  BowlFood,
  IceCream,
  Flame,
  Sparkle,
  MagicWand,
  ListChecks,
  CaretRight,
  CaretLeft,
  CaretDown,
  X,
  PencilSimple,
  Trash,
  MagnifyingGlass,
  Clock,
  ArrowRight,
  Fish,
  Cheese,
  Cookie,
  Coffee,
  Package,
  Basket,
  Storefront,
  Receipt,
  Camera,
  Heart,
  Leaf,
  Orange,
  Jar,
  Bread,
  Pepper,
  SunHorizon,
  ThermometerCold,
  WarningCircle,
  Info,
  Funnel,
  ArrowsClockwise,
  CellSignalFull,
  WifiHigh,
  BatteryFull,
  IconWeight,
} from 'phosphor-react-native';

const map = {
  house: House,
  'fork-knife': ForkKnife,
  'shopping-cart-simple': ShoppingCartSimple,
  snowflake: Snowflake,
  gear: GearSix,
  user: User,
  users: Users,
  'house-line': HouseLine,
  'cooking-pot': CookingPot,
  'check-circle': CheckCircle,
  check: Check,
  plus: Plus,
  'plus-circle': PlusCircle,
  'minus-circle': MinusCircle,
  bell: Bell,
  'bell-ringing': BellRinging,
  drop: Drop,
  cube: Cube,
  plant: Plant,
  carrot: Carrot,
  egg: Egg,
  'bowl-food': BowlFood,
  'ice-cream': IceCream,
  flame: Flame,
  sparkle: Sparkle,
  'magic-wand': MagicWand,
  'list-checks': ListChecks,
  'caret-right': CaretRight,
  'caret-left': CaretLeft,
  'caret-down': CaretDown,
  x: X,
  pencil: PencilSimple,
  trash: Trash,
  search: MagnifyingGlass,
  clock: Clock,
  'arrow-right': ArrowRight,
  fish: Fish,
  cheese: Cheese,
  cookie: Cookie,
  coffee: Coffee,
  package: Package,
  basket: Basket,
  storefront: Storefront,
  receipt: Receipt,
  camera: Camera,
  heart: Heart,
  leaf: Leaf,
  orange: Orange,
  jar: Jar,
  bread: Bread,
  pepper: Pepper,
  'sun-horizon': SunHorizon,
  'thermometer-cold': ThermometerCold,
  'warning-circle': WarningCircle,
  info: Info,
  funnel: Funnel,
  'arrows-clockwise': ArrowsClockwise,
  'cell-signal-full': CellSignalFull,
  'wifi-high': WifiHigh,
  'battery-full': BatteryFull,
} as const;

export type IconName = keyof typeof map;

export function Icon({
  name,
  size = 24,
  color = '#33352F',
  weight = 'regular',
}: {
  name: IconName;
  size?: number;
  color?: string;
  weight?: IconWeight;
}) {
  const Cmp = map[name];
  return <Cmp size={size} color={color} weight={weight} />;
}
